[[redirects]]
from = "/papers/*"
to = "/papers/index.html"
status = 404

[[redirects]]
from = "/papers/*"
to = "/papers/index.html"
status = 404

[[redirects]]
from = "/papers/*"
to = "/papers/index.html"
status = 404

[[redirects]]
from = "/papers/*"
to = "/papers/index.html"
status = 404

[[redirects]]
from = "/papers/*"
to = "/papers/index.html"
status = 404

[[redirects]]
from = "/papers/*"
to = "/papers/index.html"
status = 404

[[redirects]]
from = "/papers/*"
to = "/papers/index.html"
status = 404