[[redirects]]
from = "/about/*"
to = "/about/index.html"
status = 404

[[redirects]]
from = "/art/*"
to = "/art/index.html"
status = 404

[[redirects]]
from = "/blog/*"
to = "/blog/index.html"
status = 404

[[redirects]]
from = "/design/*"
to = "/design/index.html"
status = 404

[[redirects]]
from = "/papers/*"
to = "/papers/index.html"
status = 404

[[redirects]]
from = "/the-tree/*"
to = "/the-tree/index.html"
status = 404

[[redirects]]
from = "/*"
to = "/index.html"
status = 404